version: '3.2'
services:
  ds_test:
    container_name: ds_test
    build: .
    volumes:
      - ./testscript:/testscript
    environment:
      - QUEUE_HOST="https://141.39.156.108:443"
    command: bash -c "tail -f /dev/null" 
