version: '3.2'
services:
  ds_test:
    container_name: ds_test
    build: .
    volumes:
      - ../cert/ca_cert/ds_develop_ca.crt:/usr/local/share/ca-certificates/ds_develop_ca.crt
      - ./testscript:/testscript
    environment:
      - QUEUE_HOST="http://queue_server:443"
    command: bash -c "tail -f /dev/null" 
