version: '3.5'

services:
  queue_server:
    container_name: queue_server
    restart: unless-stopped
    build: ..
    environment:
      - TIMEOUT_QUEUE_AND_POLL=${TIMEOUT_QUEUE_AND_POLL} # define timeout for requests
      - ALLOWED_IPS=${ALLOWED_IPS}
      - LOG_LEVEL=${LOG_LEVEL} # define log level
    volumes:
      - ../../cert/do_cert/queue.key:/home/dsqueue/ds_queue/cert/queuekey.pem
      - ../../cert/do_cert/queue.crt:/home/dsqueue/ds_queue/cert/queuecert.pem
      - ..:/home/dsqueue/ds_queue
    entrypoint: bash -c "tail -f /dev/null"